### ISSUE TITLE
Create index.html and Refactor Code for Music Streaming Platform

### ISSUE THREAD

**Issue by SwayamBadhe** [mlscgescoe/Music-Streaming-Platformm#3]
### Issue: 
Currently, our Music Streaming Platform project is missing the essential index.html file, which serves as the entry point for our web application. In addition, the project's code structure can be enhanced for better organization and maintainability. This issue aims to address these two aspects:

### Proposed Changes:

1. Create index.html: Start by creating the index.html file in the project's root directory. This file will serve as the main entry point for our music streaming platform website.

2. Code Refactoring and Structure Enhancement: After creating the index.html file, refactor the existing codebase for improved readability and maintainability. Reorganize the code structure to ensure it follows best practices and is well-documented.

## Benefits:

1. Project Initialization: Creating the index.html file is a crucial step in initializing our music streaming platform website.

2. Improved Codebase: Code refactoring and structure enhancement will result in a cleaner, more organized, and maintainable codebase.

3. Better Collaboration: A well-structured project encourages collaboration from developers who can easily understand and contribute to the code.

### Acceptance Criteria:

1. An index.html file is created in the project's root directory.

2. The existing codebase is refactored to adhere to best practices, including consistent coding style and documentation.

3. Code is restructured for improved organization and maintainability.

4. The index.html file is moved out of any existing folders to the project's root directory.

## Additional Information:
This issue is an essential first step in setting up our music streaming platform website. Contributors with expertise in web development and code organization are encouraged to tackle this task.

**Comment by tanvi-yeole** [comment]
Hey, can you assign me this issue please?
